---
title: "Sample eCOTS R Markdown Example"
author: "Mine and Nick"
date: "May 17, 2016"
output: 
  pdf_document:
    fig_height: 3
    fig_width: 5
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---

```{r, include=FALSE}
# Load required packages here
require(mosaic)
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
options(digits=3)
```

This is a simple R Markdown file that illustrates how to calculate summary statistics, generate graphical displays, and fit regression models using the `Galton` height dataset.

A variant of this activity is used on the first day of the introductory statistics courses at Amherst College.

```{r}
glimpse(Galton)
```

#### Summary statistics

```{r}
favstats(height ~ sex, data=Galton)
```

#### Graphical displays

```{r}
densityplot(~ height, group=sex, auto.key=TRUE, lwd=2, data=Galton)
```

#### Regression

```{r}
mod <- lm(height ~ mother + sex, data=Galton)
coef(mod)
plotModel(mod)
mplot(mod, which=1)
```
